version: '3'

services:
    server:
        network_mode: host
        build: 
            context: ./build-server/
        environment: 
            - TOKEN=${TOKEN}
    agent:
        restart: always
        network_mode: host
        volumes:
            - ./repos:/repos
        depends_on:
            - server
        build: 
            context: ./build-agent/
        environment: 
            - PORT=3002
    agent2:
        restart: always
        network_mode: host
        volumes:
            - ./repos:/repos
        depends_on:
            - server
        build: 
            context: ./build-agent/
        environment: 
            - PORT=3004