version: '3'

services:
    server:
        network_mode: host
        build: 
            context: ./build-server/
        environment: 
            - TOKEN=${TOKEN}
    agent:
        restart: always
        network_mode: host
        depends_on:
            - server
        build: 
            context: ./build-agent/
        environment: 
            - PORT=3002
    # agent2:
    #     restart: always
    #     network_mode: host
    #     depends_on:
    #         - server
    #     build: 
    #         context: ./build-agent/
    #     environment: 
    #         - PORT=3004
    # agent3:
    #     restart: always
    #     network_mode: host
    #     depends_on:
    #         - server
    #     build: 
    #         context: ./build-agent/
    #     environment: 
    #         - PORT=3005
    # agent4:
    #     restart: always
    #     network_mode: host
    #     depends_on:
    #         - server
    #     build: 
    #         context: ./build-agent/
    #     environment: 
    #         - PORT=3006